name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure --prefix=/usr --exec-prefix=

    - name: make
      run: make CFLAGS="-O2 -Wall"

    - name: make install
      run: sudo make install

    - name: make check
      run: make check

    - name: Run distcheck
      run: make distcheck
